// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function FocusGame() {
    return $Call.ByID(722450723);
}

/**
 * @returns {$CancellablePromise<$models.EnvironmentInfo>}
 */
export function GetEnvironmentInfo() {
    return $Call.ByID(4062592230).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(376180615);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(1996570155);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReloadGame() {
    return $Call.ByID(2301748788);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReloadShell() {
    return $Call.ByID(632216624);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReturnToMainMenu() {
    return $Call.ByID(1793250278);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowEnvironment() {
    return $Call.ByID(1539102247);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowGameHelp() {
    return $Call.ByID(704623563);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(1126512694);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFullscreen() {
    return $Call.ByID(589073994);
}

// Private type creation functions
const $$createType0 = $models.EnvironmentInfo.createFrom;
