// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EnvironmentInfo {
    /**
     * Creates a new EnvironmentInfo instance.
     * @param {Partial<EnvironmentInfo>} [$$source = {}] - The source object to create the EnvironmentInfo.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("wailsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wailsVersion"] = "";
        }
        if (!("goos" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goos"] = "";
        }
        if (!("goarch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goarch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentInfo(/** @type {Partial<EnvironmentInfo>} */($$parsedSource));
    }
}
